theme: minima
plugins:
- jekyll-remote-theme

# Configurations
title: Radiator AAA Server Frequently Asked Questions
description: >
  Radiator AAA Server Frequently Asked Questions, Radiator RADIUS Server FAQ

show_downloads: false

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md
